(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"N2HDM_CPVDM",
  Authors -> {"Jonas Wittbrodt"},
  Version -> "1.0"};

FR$ClassesTranslation={ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], m -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], h -> S[1], G0 -> S[2], Gch -> S[3], H1 -> S[4], H2 -> S[5], H3 -> S[6], Hc -> S[7]};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[DarkHiggs] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnue,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnum,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> False,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnut,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MM"],
    Indices -> {},
    PropagatorLabel -> "m" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MU"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MC"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MT"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MD"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MS"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MB"],
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"],
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"],
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mHsm,
    Indices -> {},
    PropagatorLabel -> "h" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mG0,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {Q},
    Mass -> mGch,
    Indices -> {},
    PropagatorLabel -> "Gch" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mH1,
    Indices -> {},
    PropagatorLabel -> "H1" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mH2,
    Indices -> {},
    PropagatorLabel -> "H2" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mH3,
    Indices -> {},
    PropagatorLabel -> "H3" },

S[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mHc,
    Indices -> {},
    PropagatorLabel -> "Hc" }
}


(*        Definitions       *)

FAGaugeXi[ S[7] ] = FAGaugeXi[S[5]];

Mnue[ ___ ] := Mnue;
Mnum[ ___ ] := Mnum;
Mnut[ ___ ] := Mnut;
Me[ ___ ] := Me;
FCGV["MM"][ ___ ] := FCGV["MM"];
MTA[ ___ ] := MTA;
FCGV["MU"][ ___ ] := FCGV["MU"];
FCGV["MC"][ ___ ] := FCGV["MC"];
FCGV["MT"][ ___ ] := FCGV["MT"];
FCGV["MD"][ ___ ] := FCGV["MD"];
FCGV["MS"][ ___ ] := FCGV["MS"];
FCGV["MB"][ ___ ] := FCGV["MB"];
FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
mHsm[ ___ ] := mHsm;
mG0[ ___ ] := mG0;
mGch[ ___ ] := mGch;
mH1[ ___ ] := mH1;
mH2[ ___ ] := mH2;
mH3[ ___ ] := mH3;
mHc[ ___ ] := mHc;


TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-3*I)*L1, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-I)*L1, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-2*I)*L1, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-I)*L1, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-I)*L1, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*L1, 0}},

C[ S[7] , S[7] , -S[7] , -S[7] ] == {{(-2*I)*L2, 0}},

C[ S[2] , S[2] , S[7] , -S[7] ] == {{(-I)*L3, 0}},

C[ S[3] , -S[3] , S[7] , -S[7] ] == {{(-I)*(L3 + L4), 0}},

C[ S[1] , S[1] , S[7] , -S[7] ] == {{(-I)*L3, 0}},

C[ -S[3] , -S[3] , S[7] , S[7] ] == {{(-2*I)*L5, 0}},

C[ S[3] , S[3] , -S[7] , -S[7] ] == {{(-2*I)*L5, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-I)*L1*v, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-I)*L1*v, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*L1*v, 0}},

C[ S[1] , S[7] , -S[7] ] == {{(-I)*L3*v, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[7] , -S[7] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc19, 0}, {I*gc19, 0}},

C[ S[7] , -S[7] , V[1] ] == {{(-I)*gc20, 0}, {I*gc20, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc21, 0}, {I*gc21, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc22, 0}, {I*gc22, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc24, 0}, {I*gc24, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc27, 0}, {I*gc27, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc28, 0}, {I*gc28, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc30, 0}, {I*gc30, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc32, 0}, {I*gc32, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(FCGV["EL"]^2*v)/(4*FCGV["SW"]^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc35, 0}, {I*gc35, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc36, 0}, {I*gc36, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc38, 0}, {I*gc38, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc40, 0}, {I*gc40, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc42, 0}, {I*gc42, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc44*FASUNF[e3x2, e1x1, e2x1], 0}, {gc44*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc45*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc45*FASUNF[e1x2, e2x2, e3x2], 0}, {gc45*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc45*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc45*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc45*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc46*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc46*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc46*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[2] , -S[3] , S[4] , S[7] ] == {{(L4*(RR1x1 - I*RR1x2) - L5*(RR1x1 + I*RR1x2))/2, 0}},

C[ -S[3] , S[1] , S[4] , S[7] ] == {{((-I)*L4*RR1x1 - I*L5*RR1x1 - L4*RR1x2 + L5*RR1x2)/2, 0}},

C[ S[2] , S[3] , S[4] , -S[7] ] == {{(L5*(RR1x1 - I*RR1x2) - L4*(RR1x1 + I*RR1x2))/2, 0}},

C[ S[3] , S[1] , S[4] , -S[7] ] == {{(-1/2*I)*(L4*RR1x1 + L5*RR1x1 + I*L4*RR1x2 - I*L5*RR1x2), 0}},

C[ -S[3] , S[4] , S[7] ] == {{(-1/2*I)*((2*I)*RR1x3*Timag + 2*RR1x3*Treal + L4*RR1x1*v + L5*RR1x1*v - I*L4*RR1x2*v + I*L5*RR1x2*v), 0}},

C[ S[3] , S[4] , -S[7] ] == {{(-1/2*I)*(2*RR1x3*((-I)*Timag + Treal) + L5*(RR1x1 - I*RR1x2)*v + L4*(RR1x1 + I*RR1x2)*v), 0}},

C[ S[4] , S[4] , S[7] , -S[7] ] == {{(-I)*(L2*(RR1x1^2 + RR1x2^2) + L8*RR1x3^2), 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-I)*(-(L5*RR1x1^2) + L5*RR1x2^2 + L3*(RR1x1^2 + RR1x2^2) + L4*(RR1x1^2 + RR1x2^2) + L7*RR1x3^2), 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(-I)*(L3*(RR1x1^2 + RR1x2^2) + L7*RR1x3^2), 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(-I)*(L5*RR1x1^2 - L5*RR1x2^2 + L3*(RR1x1^2 + RR1x2^2) + L4*(RR1x1^2 + RR1x2^2) + L7*RR1x3^2), 0}},

C[ S[1] , S[4] , S[4] ] == {{(-I)*(-2*RR1x2*RR1x3*Timag + 2*RR1x1*RR1x3*Treal + (L3 + L4 + L5)*RR1x1^2*v + (L3 + L4 - L5)*RR1x2^2*v + L7*RR1x3^2*v), 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-3*I)*(L2*(RR1x1^2 + RR1x2^2)^2 + 2*L8*(RR1x1^2 + RR1x2^2)*RR1x3^2 + L6*RR1x3^4), 0}},

C[ S[2] , S[1] , S[4] , S[4] ] == {{(-2*I)*L5*RR1x1*RR1x2, 0}},

C[ S[2] , S[4] , S[4] ] == {{(-2*I)*(RR1x1*RR1x3*Timag + RR1x2*RR1x3*Treal + L5*RR1x1*RR1x2*v), 0}},

C[ S[2] , -S[3] , S[5] , S[7] ] == {{(L4*(RR2x1 - I*RR2x2) - L5*(RR2x1 + I*RR2x2))/2, 0}},

C[ -S[3] , S[1] , S[5] , S[7] ] == {{((-I)*L4*RR2x1 - I*L5*RR2x1 - L4*RR2x2 + L5*RR2x2)/2, 0}},

C[ S[2] , S[3] , S[5] , -S[7] ] == {{(L5*(RR2x1 - I*RR2x2) - L4*(RR2x1 + I*RR2x2))/2, 0}},

C[ S[3] , S[1] , S[5] , -S[7] ] == {{((-I)*L4*RR2x1 - I*L5*RR2x1 + L4*RR2x2 - L5*RR2x2)/2, 0}},

C[ -S[3] , S[5] , S[7] ] == {{(-1/2*I)*((2*I)*RR2x3*Timag + 2*RR2x3*Treal + L4*RR2x1*v + L5*RR2x1*v - I*L4*RR2x2*v + I*L5*RR2x2*v), 0}},

C[ S[3] , S[5] , -S[7] ] == {{-(RR2x3*(Timag + I*Treal)) + (((-I)*L5*RR2x1 - L5*RR2x2 + L4*((-I)*RR2x1 + RR2x2))*v)/2, 0}},

C[ S[4] , S[5] , S[7] , -S[7] ] == {{(-I)*(L2*RR1x1*RR2x1 + L2*RR1x2*RR2x2 + L8*RR1x3*RR2x3), 0}},

C[ S[2] , S[2] , S[4] , S[5] ] == {{(-I)*(L3*RR1x1*RR2x1 + L4*RR1x1*RR2x1 - L5*RR1x1*RR2x1 + L3*RR1x2*RR2x2 + L4*RR1x2*RR2x2 + L5*RR1x2*RR2x2 + L7*RR1x3*RR2x3), 0}},

C[ S[3] , -S[3] , S[4] , S[5] ] == {{(-I)*(L3*RR1x1*RR2x1 + L3*RR1x2*RR2x2 + L7*RR1x3*RR2x3), 0}},

C[ S[1] , S[1] , S[4] , S[5] ] == {{(-I)*(L3*RR1x1*RR2x1 + L4*RR1x1*RR2x1 + L5*RR1x1*RR2x1 + L3*RR1x2*RR2x2 + L4*RR1x2*RR2x2 - L5*RR1x2*RR2x2 + L7*RR1x3*RR2x3), 0}},

C[ S[1] , S[4] , S[5] ] == {{(-I)*(-(RR1x2*RR2x3*Timag) + RR1x1*RR2x3*Treal + (L3 + L4 + L5)*RR1x1*RR2x1*v + (L3 + L4 - L5)*RR1x2*RR2x2*v + RR1x3*(-(RR2x2*Timag) + RR2x1*Treal + L7*RR2x3*v)), 0}},

C[ S[4] , S[4] , S[4] , S[5] ] == {{(-3*I)*(L2*(RR1x1^2 + RR1x2^2)*(RR1x1*RR2x1 + RR1x2*RR2x2) + L6*RR1x3^3*RR2x3 + L8*RR1x3*(RR1x1*RR1x3*RR2x1 + RR1x2*RR1x3*RR2x2 + RR1x1^2*RR2x3 + RR1x2^2*RR2x3)), 0}},

C[ S[2] , S[1] , S[4] , S[5] ] == {{(-I)*L5*(RR1x2*RR2x1 + RR1x1*RR2x2), 0}},

C[ S[2] , S[4] , S[5] ] == {{(-I)*(RR1x3*RR2x1*Timag + RR1x1*RR2x3*Timag + RR1x3*RR2x2*Treal + RR1x2*RR2x3*Treal + L5*RR1x2*RR2x1*v + L5*RR1x1*RR2x2*v), 0}},

C[ S[5] , S[5] , S[7] , -S[7] ] == {{(-I)*(L2*(RR2x1^2 + RR2x2^2) + L8*RR2x3^2), 0}},

C[ S[2] , S[2] , S[5] , S[5] ] == {{(-I)*(-(L5*RR2x1^2) + L5*RR2x2^2 + L3*(RR2x1^2 + RR2x2^2) + L4*(RR2x1^2 + RR2x2^2) + L7*RR2x3^2), 0}},

C[ S[3] , -S[3] , S[5] , S[5] ] == {{(-I)*(L3*(RR2x1^2 + RR2x2^2) + L7*RR2x3^2), 0}},

C[ S[1] , S[1] , S[5] , S[5] ] == {{(-I)*(L5*RR2x1^2 - L5*RR2x2^2 + L3*(RR2x1^2 + RR2x2^2) + L4*(RR2x1^2 + RR2x2^2) + L7*RR2x3^2), 0}},

C[ S[1] , S[5] , S[5] ] == {{(-I)*(-2*RR2x2*RR2x3*Timag + 2*RR2x1*RR2x3*Treal + (L3 + L4 + L5)*RR2x1^2*v + (L3 + L4 - L5)*RR2x2^2*v + L7*RR2x3^2*v), 0}},

C[ S[4] , S[4] , S[5] , S[5] ] == {{(-I)*(L2*(4*RR1x1*RR1x2*RR2x1*RR2x2 + RR1x1^2*(3*RR2x1^2 + RR2x2^2) + RR1x2^2*(RR2x1^2 + 3*RR2x2^2)) + 3*L6*RR1x3^2*RR2x3^2 + L8*(RR1x3^2*(RR2x1^2 + RR2x2^2) + 4*RR1x3*(RR1x1*RR2x1 + RR1x2*RR2x2)*RR2x3 + (RR1x1^2 + RR1x2^2)*RR2x3^2)), 0}},

C[ S[4] , S[5] , S[5] , S[5] ] == {{(-3*I)*(L2*(RR1x1*RR2x1 + RR1x2*RR2x2)*(RR2x1^2 + RR2x2^2) + L6*RR1x3*RR2x3^3 + L8*RR2x3*(RR1x3*RR2x1^2 + RR1x3*RR2x2^2 + RR1x1*RR2x1*RR2x3 + RR1x2*RR2x2*RR2x3)), 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{(-3*I)*(L2*(RR2x1^2 + RR2x2^2)^2 + 2*L8*(RR2x1^2 + RR2x2^2)*RR2x3^2 + L6*RR2x3^4), 0}},

C[ S[2] , S[1] , S[5] , S[5] ] == {{(-2*I)*L5*RR2x1*RR2x2, 0}},

C[ S[2] , S[5] , S[5] ] == {{(-2*I)*(RR2x1*RR2x3*Timag + RR2x2*RR2x3*Treal + L5*RR2x1*RR2x2*v), 0}},

C[ S[2] , -S[3] , S[6] , S[7] ] == {{(L4*(RR3x1 - I*RR3x2) - L5*(RR3x1 + I*RR3x2))/2, 0}},

C[ -S[3] , S[1] , S[6] , S[7] ] == {{(-1/2*I)*(L4*RR3x1 + L5*RR3x1 - I*L4*RR3x2 + I*L5*RR3x2), 0}},

C[ S[2] , S[3] , S[6] , -S[7] ] == {{(L5*(RR3x1 - I*RR3x2) - L4*(RR3x1 + I*RR3x2))/2, 0}},

C[ S[3] , S[1] , S[6] , -S[7] ] == {{(-1/2*I)*(L4*RR3x1 + L5*RR3x1 + I*L4*RR3x2 - I*L5*RR3x2), 0}},

C[ -S[3] , S[6] , S[7] ] == {{(-1/2*I)*((2*I)*RR3x3*Timag + 2*RR3x3*Treal + L4*RR3x1*v + L5*RR3x1*v - I*L4*RR3x2*v + I*L5*RR3x2*v), 0}},

C[ S[3] , S[6] , -S[7] ] == {{-(RR3x3*(Timag + I*Treal)) + (((-I)*L5*RR3x1 - L5*RR3x2 + L4*((-I)*RR3x1 + RR3x2))*v)/2, 0}},

C[ S[4] , S[6] , S[7] , -S[7] ] == {{(-I)*(L2*RR1x1*RR3x1 + L2*RR1x2*RR3x2 + L8*RR1x3*RR3x3), 0}},

C[ S[2] , S[2] , S[4] , S[6] ] == {{(-I)*(L3*RR1x1*RR3x1 + L4*RR1x1*RR3x1 - L5*RR1x1*RR3x1 + L3*RR1x2*RR3x2 + L4*RR1x2*RR3x2 + L5*RR1x2*RR3x2 + L7*RR1x3*RR3x3), 0}},

C[ S[3] , -S[3] , S[4] , S[6] ] == {{(-I)*(L3*RR1x1*RR3x1 + L3*RR1x2*RR3x2 + L7*RR1x3*RR3x3), 0}},

C[ S[1] , S[1] , S[4] , S[6] ] == {{(-I)*(L3*RR1x1*RR3x1 + L4*RR1x1*RR3x1 + L5*RR1x1*RR3x1 + L3*RR1x2*RR3x2 + L4*RR1x2*RR3x2 - L5*RR1x2*RR3x2 + L7*RR1x3*RR3x3), 0}},

C[ S[1] , S[4] , S[6] ] == {{(-I)*(-(RR1x2*RR3x3*Timag) + RR1x1*RR3x3*Treal + (L3 + L4 + L5)*RR1x1*RR3x1*v + (L3 + L4 - L5)*RR1x2*RR3x2*v + RR1x3*(-(RR3x2*Timag) + RR3x1*Treal + L7*RR3x3*v)), 0}},

C[ S[4] , S[4] , S[4] , S[6] ] == {{(-3*I)*(L2*(RR1x1^2 + RR1x2^2)*(RR1x1*RR3x1 + RR1x2*RR3x2) + L6*RR1x3^3*RR3x3 + L8*RR1x3*(RR1x1*RR1x3*RR3x1 + RR1x2*RR1x3*RR3x2 + RR1x1^2*RR3x3 + RR1x2^2*RR3x3)), 0}},

C[ S[2] , S[1] , S[4] , S[6] ] == {{(-I)*L5*(RR1x2*RR3x1 + RR1x1*RR3x2), 0}},

C[ S[2] , S[4] , S[6] ] == {{(-I)*(RR1x3*RR3x1*Timag + RR1x1*RR3x3*Timag + RR1x3*RR3x2*Treal + RR1x2*RR3x3*Treal + L5*RR1x2*RR3x1*v + L5*RR1x1*RR3x2*v), 0}},

C[ S[5] , S[6] , S[7] , -S[7] ] == {{(-I)*(L2*RR2x1*RR3x1 + L2*RR2x2*RR3x2 + L8*RR2x3*RR3x3), 0}},

C[ S[2] , S[2] , S[5] , S[6] ] == {{(-I)*(L3*RR2x1*RR3x1 + L4*RR2x1*RR3x1 - L5*RR2x1*RR3x1 + L3*RR2x2*RR3x2 + L4*RR2x2*RR3x2 + L5*RR2x2*RR3x2 + L7*RR2x3*RR3x3), 0}},

C[ S[3] , -S[3] , S[5] , S[6] ] == {{(-I)*(L3*RR2x1*RR3x1 + L3*RR2x2*RR3x2 + L7*RR2x3*RR3x3), 0}},

C[ S[1] , S[1] , S[5] , S[6] ] == {{(-I)*(L3*RR2x1*RR3x1 + L4*RR2x1*RR3x1 + L5*RR2x1*RR3x1 + L3*RR2x2*RR3x2 + L4*RR2x2*RR3x2 - L5*RR2x2*RR3x2 + L7*RR2x3*RR3x3), 0}},

C[ S[1] , S[5] , S[6] ] == {{(-I)*(-(RR2x2*RR3x3*Timag) + RR2x1*RR3x3*Treal + (L3 + L4 + L5)*RR2x1*RR3x1*v + (L3 + L4 - L5)*RR2x2*RR3x2*v + RR2x3*(-(RR3x2*Timag) + RR3x1*Treal + L7*RR3x3*v)), 0}},

C[ S[4] , S[4] , S[5] , S[6] ] == {{(-I)*(L2*(2*RR1x1*RR1x2*(RR2x2*RR3x1 + RR2x1*RR3x2) + RR1x1^2*(3*RR2x1*RR3x1 + RR2x2*RR3x2) + RR1x2^2*(RR2x1*RR3x1 + 3*RR2x2*RR3x2)) + 3*L6*RR1x3^2*RR2x3*RR3x3 + L8*(RR1x3^2*(RR2x1*RR3x1 + RR2x2*RR3x2) + (RR1x1^2 + RR1x2^2)*RR2x3*RR3x3 + 2*RR1x3*(RR1x1*RR2x3*RR3x1 + RR1x2*RR2x3*RR3x2 + RR1x1*RR2x1*RR3x3 + RR1x2*RR2x2*RR3x3))), 0}},

C[ S[4] , S[5] , S[5] , S[6] ] == {{(-I)*(L2*(RR1x1*(3*RR2x1^2*RR3x1 + RR2x2^2*RR3x1 + 2*RR2x1*RR2x2*RR3x2) + RR1x2*(2*RR2x1*RR2x2*RR3x1 + RR2x1^2*RR3x2 + 3*RR2x2^2*RR3x2)) + 3*L6*RR1x3*RR2x3^2*RR3x3 + L8*RR2x3*(RR1x1*RR2x3*RR3x1 + RR1x2*RR2x3*RR3x2 + 2*RR1x1*RR2x1*RR3x3 + 2*RR1x2*RR2x2*RR3x3) + L8*RR1x3*(2*RR2x1*RR2x3*RR3x1 + RR2x1^2*RR3x3 + RR2x2*(2*RR2x3*RR3x2 + RR2x2*RR3x3))), 0}},

C[ S[5] , S[5] , S[5] , S[6] ] == {{(-3*I)*(L2*(RR2x1^2 + RR2x2^2)*(RR2x1*RR3x1 + RR2x2*RR3x2) + L6*RR2x3^3*RR3x3 + L8*RR2x3*(RR2x1*RR2x3*RR3x1 + RR2x2*RR2x3*RR3x2 + RR2x1^2*RR3x3 + RR2x2^2*RR3x3)), 0}},

C[ S[2] , S[1] , S[5] , S[6] ] == {{(-I)*L5*(RR2x2*RR3x1 + RR2x1*RR3x2), 0}},

C[ S[2] , S[5] , S[6] ] == {{(-I)*(RR2x3*RR3x1*Timag + RR2x1*RR3x3*Timag + RR2x3*RR3x2*Treal + RR2x2*RR3x3*Treal + L5*RR2x2*RR3x1*v + L5*RR2x1*RR3x2*v), 0}},

C[ S[6] , S[6] , S[7] , -S[7] ] == {{(-I)*(L2*(RR3x1^2 + RR3x2^2) + L8*RR3x3^2), 0}},

C[ S[2] , S[2] , S[6] , S[6] ] == {{(-I)*(-(L5*RR3x1^2) + L5*RR3x2^2 + L3*(RR3x1^2 + RR3x2^2) + L4*(RR3x1^2 + RR3x2^2) + L7*RR3x3^2), 0}},

C[ S[3] , -S[3] , S[6] , S[6] ] == {{(-I)*(L3*(RR3x1^2 + RR3x2^2) + L7*RR3x3^2), 0}},

C[ S[1] , S[1] , S[6] , S[6] ] == {{(-I)*(L5*RR3x1^2 - L5*RR3x2^2 + L3*(RR3x1^2 + RR3x2^2) + L4*(RR3x1^2 + RR3x2^2) + L7*RR3x3^2), 0}},

C[ S[1] , S[6] , S[6] ] == {{(-I)*(-2*RR3x2*RR3x3*Timag + 2*RR3x1*RR3x3*Treal + (L3 + L4 + L5)*RR3x1^2*v + (L3 + L4 - L5)*RR3x2^2*v + L7*RR3x3^2*v), 0}},

C[ S[4] , S[4] , S[6] , S[6] ] == {{(-I)*(L2*(4*RR1x1*RR1x2*RR3x1*RR3x2 + RR1x1^2*(3*RR3x1^2 + RR3x2^2) + RR1x2^2*(RR3x1^2 + 3*RR3x2^2)) + 3*L6*RR1x3^2*RR3x3^2 + L8*(RR1x3^2*(RR3x1^2 + RR3x2^2) + 4*RR1x3*(RR1x1*RR3x1 + RR1x2*RR3x2)*RR3x3 + (RR1x1^2 + RR1x2^2)*RR3x3^2)), 0}},

C[ S[4] , S[5] , S[6] , S[6] ] == {{(-I)*(L8*RR1x3*RR2x3*(RR3x1^2 + RR3x2^2) + L2*RR1x1*(2*RR2x2*RR3x1*RR3x2 + RR2x1*(3*RR3x1^2 + RR3x2^2)) + L2*RR1x2*(2*RR2x1*RR3x1*RR3x2 + RR2x2*(RR3x1^2 + 3*RR3x2^2)) + 2*L8*RR1x3*(RR2x1*RR3x1 + RR2x2*RR3x2)*RR3x3 + 3*L6*RR1x3*RR2x3*RR3x3^2 + L8*RR3x3*(2*RR1x1*RR2x3*RR3x1 + 2*RR1x2*RR2x3*RR3x2 + RR1x1*RR2x1*RR3x3 + RR1x2*RR2x2*RR3x3)), 0}},

C[ S[5] , S[5] , S[6] , S[6] ] == {{(-I)*(L2*(4*RR2x1*RR2x2*RR3x1*RR3x2 + RR2x1^2*(3*RR3x1^2 + RR3x2^2) + RR2x2^2*(RR3x1^2 + 3*RR3x2^2)) + 3*L6*RR2x3^2*RR3x3^2 + L8*(RR2x3^2*(RR3x1^2 + RR3x2^2) + 4*RR2x3*(RR2x1*RR3x1 + RR2x2*RR3x2)*RR3x3 + (RR2x1^2 + RR2x2^2)*RR3x3^2)), 0}},

C[ S[4] , S[6] , S[6] , S[6] ] == {{(-3*I)*(L2*(RR1x1*RR3x1 + RR1x2*RR3x2)*(RR3x1^2 + RR3x2^2) + L6*RR1x3*RR3x3^3 + L8*RR3x3*(RR1x3*RR3x1^2 + RR1x3*RR3x2^2 + RR1x1*RR3x1*RR3x3 + RR1x2*RR3x2*RR3x3)), 0}},

C[ S[5] , S[6] , S[6] , S[6] ] == {{(-3*I)*(L2*(RR2x1*RR3x1 + RR2x2*RR3x2)*(RR3x1^2 + RR3x2^2) + L6*RR2x3*RR3x3^3 + L8*RR3x3*(RR2x3*RR3x1^2 + RR2x3*RR3x2^2 + RR2x1*RR3x1*RR3x3 + RR2x2*RR3x2*RR3x3)), 0}},

C[ S[6] , S[6] , S[6] , S[6] ] == {{(-3*I)*(L2*(RR3x1^2 + RR3x2^2)^2 + 2*L8*(RR3x1^2 + RR3x2^2)*RR3x3^2 + L6*RR3x3^4), 0}},

C[ S[2] , S[1] , S[6] , S[6] ] == {{(-2*I)*L5*RR3x1*RR3x2, 0}},

C[ S[2] , S[6] , S[6] ] == {{(-2*I)*(RR3x1*RR3x3*Timag + RR3x2*RR3x3*Treal + L5*RR3x1*RR3x2*v), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*gc122*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc122*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*gc123*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc123*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*gc124*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc124*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*gc125*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc125*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*gc126*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc126*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*gc127*FASUNT[e3x2, e1x2, e2x2], 0}, {I*gc127*FASUNT[e3x2, e1x2, e2x2], 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ -S[3] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ S[2] , -S[3] , V[3] ] == {{-gc131, 0}, {gc131, 0}},

C[ -S[3] , S[1] , V[3] ] == {{(-I)*gc132, 0}, {I*gc132, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc133, 0}, {I*gc133, 0}, {I*gc133, 0}, {(-I)*gc133, 0}, {(-I)*gc133, 0}, {I*gc133, 0}},

C[ S[4] , -S[7] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1 + I*RR1x2))/FCGV["SW"], 0}},

C[ S[4] , -S[7] , V[3] ] == {{I*gc135*(RR1x1 + I*RR1x2), 0}, {gc135*((-I)*RR1x1 + RR1x2), 0}},

C[ S[5] , -S[7] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1 + I*RR2x2))/FCGV["SW"], 0}},

C[ S[5] , -S[7] , V[3] ] == {{I*gc137*(RR2x1 + I*RR2x2), 0}, {gc137*((-I)*RR2x1 + RR2x2), 0}},

C[ S[6] , -S[7] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR3x1 + I*RR3x2))/FCGV["SW"], 0}},

C[ S[6] , -S[7] , V[3] ] == {{I*gc139*(RR3x1 + I*RR3x2), 0}, {gc139*((-I)*RR3x1 + RR3x2), 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[3] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ S[2] , S[3] , -V[3] ] == {{-gc143, 0}, {gc143, 0}},

C[ S[3] , S[1] , -V[3] ] == {{(-I)*gc144, 0}, {I*gc144, 0}},

C[ S[4] , S[7] , V[1] , -V[3] ] == {{(FCGV["EL"]^2*(I*RR1x1 + RR1x2))/(2*FCGV["SW"]), 0}},

C[ S[4] , S[7] , -V[3] ] == {{-((gc146*(I*RR1x1 + RR1x2))/(RR1x1 + RR1x2)), 0}, {(gc146*(I*RR1x1 + RR1x2))/(RR1x1 + RR1x2), 0}},

C[ S[5] , S[7] , V[1] , -V[3] ] == {{(FCGV["EL"]^2*(I*RR2x1 + RR2x2))/(2*FCGV["SW"]), 0}},

C[ S[5] , S[7] , -V[3] ] == {{-((gc148*(I*RR2x1 + RR2x2))/(RR2x1 + RR2x2)), 0}, {(gc148*(I*RR2x1 + RR2x2))/(RR2x1 + RR2x2), 0}},

C[ S[6] , S[7] , V[1] , -V[3] ] == {{(FCGV["EL"]^2*(I*RR3x1 + RR3x2))/(2*FCGV["SW"]), 0}},

C[ S[6] , S[7] , -V[3] ] == {{-((gc150*(I*RR3x1 + RR3x2))/(RR3x1 + RR3x2)), 0}, {(gc150*(I*RR3x1 + RR3x2))/(RR3x1 + RR3x2), 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[7] , -S[7] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc156, 0}, {(-I)*gc156, 0}, {(2*I)*gc156, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1^2 + RR1x2^2))/FCGV["SW"]^2, 0}},

C[ S[4] , S[5] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1*RR2x1 + RR1x2*RR2x2))/FCGV["SW"]^2, 0}},

C[ S[5] , S[5] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1^2 + RR2x2^2))/FCGV["SW"]^2, 0}},

C[ S[4] , S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1*RR3x1 + RR1x2*RR3x2))/FCGV["SW"]^2, 0}},

C[ S[5] , S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1*RR3x1 + RR2x2*RR3x2))/FCGV["SW"]^2, 0}},

C[ S[6] , S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2*(RR3x1^2 + RR3x2^2))/FCGV["SW"]^2, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc163, 0}, {I*gc163, 0}, {I*gc163, 0}, {(-I)*gc163, 0}, {(-I)*gc163, 0}, {I*gc163, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc164, 0}, {(-I)*gc164, 0}, {(2*I)*gc164, 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{gc165L*IndexDelta[e1x2, e2x2], 0}, {gc165R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{I*gc166*IndexDelta[e1x2, e2x2], 0}, {I*gc166*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{I*gc167L*IndexDelta[e1x2, e2x2], 0}, {I*gc167R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{I*gc168L*IndexDelta[e1x2, e2x2], 0}, {I*gc168R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{I*gc169L*IndexDelta[e1x2, e2x2], 0}, {I*gc169R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{I*gc170L*IndexDelta[e1x2, e2x2], 0}, {I*gc170R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{I*gc171L*IndexDelta[e1x2, e2x2], 0}, {I*gc171R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{I*gc172L*IndexDelta[e1x2, e2x2], 0}, {I*gc172R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{gc173L*IndexDelta[e1x2, e2x2], 0}, {gc173R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{I*gc174*IndexDelta[e1x2, e2x2], 0}, {I*gc174*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{I*gc175L*IndexDelta[e1x2, e2x2], 0}, {I*gc175R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{I*gc176L*IndexDelta[e1x2, e2x2], 0}, {I*gc176R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{I*gc177L*IndexDelta[e1x2, e2x2], 0}, {I*gc177R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{I*gc178L*IndexDelta[e1x2, e2x2], 0}, {I*gc178R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{I*gc179L*IndexDelta[e1x2, e2x2], 0}, {I*gc179R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{I*gc180L*IndexDelta[e1x2, e2x2], 0}, {I*gc180R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{gc181L*IndexDelta[e1x2, e2x2], 0}, {gc181R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{I*gc182*IndexDelta[e1x2, e2x2], 0}, {I*gc182*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{I*gc183L*IndexDelta[e1x2, e2x2], 0}, {I*gc183R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{I*gc184L*IndexDelta[e1x2, e2x2], 0}, {I*gc184R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{I*gc185L*IndexDelta[e1x2, e2x2], 0}, {I*gc185R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{I*gc186L*IndexDelta[e1x2, e2x2], 0}, {I*gc186R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{I*gc187L*IndexDelta[e1x2, e2x2], 0}, {I*gc187R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{I*gc188L*IndexDelta[e1x2, e2x2], 0}, {I*gc188R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , S[2] ] == {{gc189L, 0}, {gc189R, 0}},

C[ -F[4] , F[4] , S[1] ] == {{I*gc190, 0}, {I*gc190, 0}},

C[ -F[4] , F[1] , -S[3] ] == {{I*gc191, 0}, {0, 0}},

C[ -F[1] , F[4] , S[3] ] == {{0, 0}, {I*gc192R, 0}},

C[ -F[5] , F[5] , S[2] ] == {{gc193L, 0}, {gc193R, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc194, 0}, {I*gc194, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{I*gc195, 0}, {0, 0}},

C[ -F[2] , F[5] , S[3] ] == {{0, 0}, {I*gc196R, 0}},

C[ -F[6] , F[6] , S[2] ] == {{gc197L, 0}, {gc197R, 0}},

C[ -F[6] , F[6] , S[1] ] == {{I*gc198, 0}, {I*gc198, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{I*gc199, 0}, {0, 0}},

C[ -F[3] , F[6] , S[3] ] == {{0, 0}, {I*gc200R, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{gc201L*IndexDelta[e1x2, e2x2], 0}, {gc201R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{I*gc202*IndexDelta[e1x2, e2x2], 0}, {I*gc202*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{gc203L*IndexDelta[e1x2, e2x2], 0}, {gc203R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{I*gc204*IndexDelta[e1x2, e2x2], 0}, {I*gc204*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{gc205L*IndexDelta[e1x2, e2x2], 0}, {gc205R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{I*gc206*IndexDelta[e1x2, e2x2], 0}, {I*gc206*IndexDelta[e1x2, e2x2], 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[7] , -S[7] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc209, 0}, {gc209, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc210, 0}, {I*gc210, 0}},

C[ S[7] , -S[7] , V[2] ] == {{(-I)*gc211, 0}, {I*gc211, 0}},

C[ S[4] , S[5] , V[2] ] == {{-gc212, 0}, {gc212, 0}},

C[ S[4] , S[6] , V[2] ] == {{-gc213, 0}, {gc213, 0}},

C[ S[5] , S[6] , V[2] ] == {{-gc214, 0}, {gc214, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ -S[3] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["CW"], 0}},

C[ S[4] , -S[7] , V[3] , V[2] ] == {{(FCGV["EL"]^2*((-I)*RR1x1 + RR1x2))/(2*FCGV["CW"]), 0}},

C[ S[5] , -S[7] , V[3] , V[2] ] == {{(FCGV["EL"]^2*((-I)*RR2x1 + RR2x2))/(2*FCGV["CW"]), 0}},

C[ S[6] , -S[7] , V[3] , V[2] ] == {{(FCGV["EL"]^2*((-I)*RR3x1 + RR3x2))/(2*FCGV["CW"]), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[3] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["CW"], 0}},

C[ S[4] , S[7] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*(RR1x1 - I*RR1x2))/FCGV["CW"], 0}},

C[ S[5] , S[7] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*(RR2x1 - I*RR2x2))/FCGV["CW"], 0}},

C[ S[6] , S[7] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2*(RR3x1 - I*RR3x2))/FCGV["CW"], 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc227, 0}, {I*gc227, 0}, {I*gc227, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[7] , -S[7] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1^2 + RR1x2^2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[5] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1*RR2x1 + RR1x2*RR2x2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[5] , S[5] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1^2 + RR2x2^2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR1x1*RR3x1 + RR1x2*RR3x2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[5] , S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR2x1*RR3x1 + RR2x2*RR3x2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[6] , S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(RR3x1^2 + RR3x2^2)*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc239, 0}, {(-I)*gc239, 0}, {(2*I)*gc239, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{I*gc240*IndexDelta[e1x2, e2x2], 0}, {I*gc240*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{I*gc241*IndexDelta[e1x2, e2x2], 0}, {I*gc241*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{I*gc242*IndexDelta[e1x2, e2x2], 0}, {I*gc242*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[1] ] == {{I*gc243, 0}, {I*gc243, 0}},

C[ -F[5] , F[5] , V[1] ] == {{I*gc244, 0}, {I*gc244, 0}},

C[ -F[6] , F[6] , V[1] ] == {{I*gc245, 0}, {I*gc245, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{I*gc246*IndexDelta[e1x2, e2x2], 0}, {I*gc246*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{I*gc247*IndexDelta[e1x2, e2x2], 0}, {I*gc247*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{I*gc248*IndexDelta[e1x2, e2x2], 0}, {I*gc248*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[4] , V[3] ] == {{I*gc249, 0}, {0, 0}},

C[ -F[2] , F[5] , V[3] ] == {{I*gc250, 0}, {0, 0}},

C[ -F[3] , F[6] , V[3] ] == {{I*gc251, 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc252*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc253*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc254*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc255*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc256*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc257*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{I*gc258*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{I*gc259*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{I*gc260*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{I*gc261, 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{I*gc262, 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{I*gc263, 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc264*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc265*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc266*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc267*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc268*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc269*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{I*gc270*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{I*gc271*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{I*gc272*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{I*gc273L*IndexDelta[e1x2, e2x2], 0}, {I*gc273R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{I*gc274L*IndexDelta[e1x2, e2x2], 0}, {I*gc274R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{I*gc275L*IndexDelta[e1x2, e2x2], 0}, {I*gc275R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4] , F[4] , V[2] ] == {{I*gc276L, 0}, {I*gc276R, 0}},

C[ -F[5] , F[5] , V[2] ] == {{I*gc277L, 0}, {I*gc277R, 0}},

C[ -F[6] , F[6] , V[2] ] == {{I*gc278L, 0}, {I*gc278R, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{I*gc279L*IndexDelta[e1x2, e2x2], 0}, {I*gc279R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{I*gc280L*IndexDelta[e1x2, e2x2], 0}, {I*gc280R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{I*gc281L*IndexDelta[e1x2, e2x2], 0}, {I*gc281R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1] , F[1] , V[2] ] == {{I*gc282, 0}, {0, 0}},

C[ -F[2] , F[2] , V[2] ] == {{I*gc283, 0}, {0, 0}},

C[ -F[3] , F[3] , V[2] ] == {{I*gc284, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc19 -> -FCGV["EL"],
     gc20 -> -FCGV["EL"],
     gc21 -> FCGV["EL"],
     gc22 -> -FCGV["EL"],
     gc24 -> FCGV["EL"],
     gc27 -> -FCGV["EL"],
     gc28 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc30 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc32 -> -FCGV["EL"],
     gc35 -> FCGV["EL"],
     gc36 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc38 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc40 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc42 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc44 -> FAGS,
     gc45 -> -FAGS,
     gc46 -> -FAGS^2,
     gc122 -> FAGS,
     gc123 -> FAGS,
     gc124 -> FAGS,
     gc125 -> FAGS,
     gc126 -> FAGS,
     gc127 -> FAGS,
     gc131 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc132 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc133 -> FCGV["EL"],
     gc135 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc137 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc139 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc143 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc144 -> -1/2*FCGV["EL"]/FCGV["SW"],
     gc146 -> (FCGV["EL"]*(RR1x1 + RR1x2))/(2*FCGV["SW"]),
     gc148 -> (FCGV["EL"]*(RR2x1 + RR2x2))/(2*FCGV["SW"]),
     gc150 -> (FCGV["EL"]*(RR3x1 + RR3x2))/(2*FCGV["SW"]),
     gc156 -> -FCGV["EL"]^2,
     gc163 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc164 -> FCGV["EL"]^2/FCGV["SW"]^2,
     gc165L -> -(yd1/Sqrt[2]),
     gc165R -> yd1/Sqrt[2],
     gc166 -> -(yd1/Sqrt[2]),
     gc167L -> -(yd1*Conjugate[CKM1x3]),
     gc167R -> yu3*Conjugate[CKM1x3],
     gc168L -> -(yd1*Conjugate[CKM1x1]),
     gc168R -> yu1*Conjugate[CKM1x1],
     gc169L -> -(yd1*Conjugate[CKM1x2]),
     gc169R -> yu2*Conjugate[CKM1x2],
     gc170L -> CKM1x3*yu3,
     gc170R -> -(CKM1x3*yd1),
     gc171L -> CKM1x1*yu1,
     gc171R -> -(CKM1x1*yd1),
     gc172L -> CKM1x2*yu2,
     gc172R -> -(CKM1x2*yd1),
     gc173L -> -(yd2/Sqrt[2]),
     gc173R -> yd2/Sqrt[2],
     gc174 -> -(yd2/Sqrt[2]),
     gc175L -> -(yd2*Conjugate[CKM2x3]),
     gc175R -> yu3*Conjugate[CKM2x3],
     gc176L -> -(yd2*Conjugate[CKM2x1]),
     gc176R -> yu1*Conjugate[CKM2x1],
     gc177L -> -(yd2*Conjugate[CKM2x2]),
     gc177R -> yu2*Conjugate[CKM2x2],
     gc178L -> CKM2x3*yu3,
     gc178R -> -(CKM2x3*yd2),
     gc179L -> CKM2x1*yu1,
     gc179R -> -(CKM2x1*yd2),
     gc180L -> CKM2x2*yu2,
     gc180R -> -(CKM2x2*yd2),
     gc181L -> -(yd3/Sqrt[2]),
     gc181R -> yd3/Sqrt[2],
     gc182 -> -(yd3/Sqrt[2]),
     gc183L -> -(yd3*Conjugate[CKM3x3]),
     gc183R -> yu3*Conjugate[CKM3x3],
     gc184L -> -(yd3*Conjugate[CKM3x1]),
     gc184R -> yu1*Conjugate[CKM3x1],
     gc185L -> -(yd3*Conjugate[CKM3x2]),
     gc185R -> yu2*Conjugate[CKM3x2],
     gc186L -> CKM3x3*yu3,
     gc186R -> -(CKM3x3*yd3),
     gc187L -> CKM3x1*yu1,
     gc187R -> -(CKM3x1*yd3),
     gc188L -> CKM3x2*yu2,
     gc188R -> -(CKM3x2*yd3),
     gc189L -> -(yl1/Sqrt[2]),
     gc189R -> yl1/Sqrt[2],
     gc190 -> -(yl1/Sqrt[2]),
     gc191 -> -yl1,
     gc192R -> -yl1,
     gc193L -> -(yl2/Sqrt[2]),
     gc193R -> yl2/Sqrt[2],
     gc194 -> -(yl2/Sqrt[2]),
     gc195 -> -yl2,
     gc196R -> -yl2,
     gc197L -> -(yl3/Sqrt[2]),
     gc197R -> yl3/Sqrt[2],
     gc198 -> -(yl3/Sqrt[2]),
     gc199 -> -yl3,
     gc200R -> -yl3,
     gc201L -> yu1/Sqrt[2],
     gc201R -> -(yu1/Sqrt[2]),
     gc202 -> -(yu1/Sqrt[2]),
     gc203L -> yu2/Sqrt[2],
     gc203R -> -(yu2/Sqrt[2]),
     gc204 -> -(yu2/Sqrt[2]),
     gc205L -> yu3/Sqrt[2],
     gc205R -> -(yu3/Sqrt[2]),
     gc206 -> -(yu3/Sqrt[2]),
     gc209 -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc210 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc211 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc212 -> -1/2*(FCGV["EL"]*(RR1x2*RR2x1 - RR1x1*RR2x2)*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc213 -> -1/2*(FCGV["EL"]*(RR1x2*RR3x1 - RR1x1*RR3x2)*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc214 -> -1/2*(FCGV["EL"]*(RR2x2*RR3x1 - RR2x1*RR3x2)*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc227 -> (FCGV["CW"]*FCGV["EL"]^2)/FCGV["SW"],
     gc239 -> -((FCGV["CW"]^2*FCGV["EL"]^2)/FCGV["SW"]^2),
     gc240 -> -1/3*FCGV["EL"],
     gc241 -> -1/3*FCGV["EL"],
     gc242 -> -1/3*FCGV["EL"],
     gc243 -> -FCGV["EL"],
     gc244 -> -FCGV["EL"],
     gc245 -> -FCGV["EL"],
     gc246 -> (2*FCGV["EL"])/3,
     gc247 -> (2*FCGV["EL"])/3,
     gc248 -> (2*FCGV["EL"])/3,
     gc249 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc250 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc251 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc252 -> (CKM2x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc253 -> (CKM2x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc254 -> (CKM2x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc255 -> (CKM3x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc256 -> (CKM3x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc257 -> (CKM3x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc258 -> (CKM1x3*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc259 -> (CKM1x1*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc260 -> (CKM1x2*FCGV["EL"])/(Sqrt[2]*FCGV["SW"]),
     gc261 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc262 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc263 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc264 -> (FCGV["EL"]*Conjugate[CKM2x3])/(Sqrt[2]*FCGV["SW"]),
     gc265 -> (FCGV["EL"]*Conjugate[CKM3x3])/(Sqrt[2]*FCGV["SW"]),
     gc266 -> (FCGV["EL"]*Conjugate[CKM1x3])/(Sqrt[2]*FCGV["SW"]),
     gc267 -> (FCGV["EL"]*Conjugate[CKM2x1])/(Sqrt[2]*FCGV["SW"]),
     gc268 -> (FCGV["EL"]*Conjugate[CKM3x1])/(Sqrt[2]*FCGV["SW"]),
     gc269 -> (FCGV["EL"]*Conjugate[CKM1x1])/(Sqrt[2]*FCGV["SW"]),
     gc270 -> (FCGV["EL"]*Conjugate[CKM2x2])/(Sqrt[2]*FCGV["SW"]),
     gc271 -> (FCGV["EL"]*Conjugate[CKM3x2])/(Sqrt[2]*FCGV["SW"]),
     gc272 -> (FCGV["EL"]*Conjugate[CKM1x2])/(Sqrt[2]*FCGV["SW"]),
     gc273L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc273R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc274L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc274R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc275L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc275R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc276L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc276R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc277L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc277R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc278L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc278R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc279L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc279R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc280L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc280R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc281L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc281R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc282 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc283 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"]),
     gc284 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"])};

